### ISSUE TITLE
What about forking the official repo instead? :)

### ISSUE THREAD

**Issue by mikrosk** [ArmstrongJ/MiNTLib#1]
https://github.com/freemint/mintlib

Also, if you have gotten anywhere with your wide char support etc, feel free to make a PR!

**Comment by ArmstrongJ** [comment]
This repo predates MiNTLib's presence on github, hence why it was originally forked from CVS.  The wide character support has [long since been committed](https://github.com/freemint/mintlib/commit/fb851abcea93fbb51a92113ce8aab1c4452e8a21).  I haven't really touched anything related to MiNT in years, though.

**Comment by ArmstrongJ** [comment]
I will add that I'm not adverse to contributing.  I just haven't really been involved with Atari stuff in a while.  The toolchain seems quite fractured at this point, and my TT is pretty much stock SpareMint.  It seems the other Atari folks have moved on from SpareMint and GCC 2.95.

**Comment by mikrosk** [comment]
No problem. I'm just mentioning this just in case you'd consider further development. And you're right, these days we compile stuff with 4.6.4 and there has been a port of 6.2 lately.
